top_srcdir   = /home/osnapadmin/CIS322/httpd-2.4.25
top_builddir = /home/osnapadmin/CIS322/httpd-2.4.25
srcdir       = /home/osnapadmin/CIS322/httpd-2.4.25/server/mpm
builddir     = /home/osnapadmin/CIS322/httpd-2.4.25/server/mpm
VPATH        = /home/osnapadmin/CIS322/httpd-2.4.25/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
