top_srcdir   = /home/osnapadmin/CIS322/httpd-2.4.25
top_builddir = /home/osnapadmin/CIS322/httpd-2.4.25
srcdir       = /home/osnapadmin/CIS322/httpd-2.4.25/server/mpm/event
builddir     = /home/osnapadmin/CIS322/httpd-2.4.25/server/mpm/event
VPATH        = /home/osnapadmin/CIS322/httpd-2.4.25/server/mpm/event
include $(top_srcdir)/build/special.mk
