top_srcdir   = /home/osnapadmin/CIS322/httpd-2.4.25
top_builddir = /home/osnapadmin/CIS322/httpd-2.4.25
srcdir       = /home/osnapadmin/CIS322/httpd-2.4.25/modules/http
builddir     = /home/osnapadmin/CIS322/httpd-2.4.25/modules/http
VPATH        = /home/osnapadmin/CIS322/httpd-2.4.25/modules/http

include $(top_srcdir)/build/special.mk

