top_srcdir   = /home/osnapadmin/CIS322/httpd-2.4.25
top_builddir = /home/osnapadmin/CIS322/httpd-2.4.25
srcdir       = /home/osnapadmin/CIS322/httpd-2.4.25/srclib
builddir     = /home/osnapadmin/CIS322/httpd-2.4.25/srclib
VPATH        = /home/osnapadmin/CIS322/httpd-2.4.25/srclib

BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
