top_srcdir   = /home/osnapadmin/CIS322/httpd-2.4.25
top_builddir = /home/osnapadmin/CIS322/httpd-2.4.25
srcdir       = /home/osnapadmin/CIS322/httpd-2.4.25/modules/core
builddir     = /home/osnapadmin/CIS322/httpd-2.4.25/modules/core
VPATH        = /home/osnapadmin/CIS322/httpd-2.4.25/modules/core

include $(top_srcdir)/build/special.mk

